# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60fd9c25e760610c2c923fd10aef21d33be02c207fad30a3bc051f3780ddc61a08f875d3687e64a4f37bede1b645f2600331ac5133d4c1d2cdd1e9cd4037f4dc

test:
  secret_key_base: 6be3bd9f1fb3a3d065e0c68a86a745ebf8a55efc4d8c9a6c1f11b6f1a8ffa0aee124978782fda61f9b460516105886ee0355b72b49910798352dd3449c8e31e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
